apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: us-central1-docker.pkg.dev/solid-altar-444910-c9/web-app-repo/web-app:latest
          ports:
            - containerPort: 80
